;; Disassembled with BadBoy Disassembler: https://github.com/daid/BadBoy



;@jumptable amount=256 label=scriptOpCode%02X
scriptOpcodeTable:
    dw   scriptOpCodeEND                               ;; 02:4576 ..
    dw   scriptOpCode01                                ;; 02:4578 ..
    dw   scriptOpCode02                                ;; 02:457a ..
    dw   scriptOpCode03                                ;; 02:457c ..
    dw   scriptOpCode04                                ;; 02:457e ..
    dw   scriptOpCodeDF                                ;; 02:4580 ??
    dw   scriptOpCodeDF                                ;; 02:4582 ??
    dw   scriptOpCodeDF                                ;; 02:4584 ??
    dw   scriptOpCode08                                ;; 02:4586 ..
    dw   scriptOpCode09                                ;; 02:4588 ..
    dw   scriptOpCode0A                                ;; 02:458a ..
    dw   scriptOpCode0B                                ;; 02:458c ..
    dw   scriptOpCode0C                                ;; 02:458e ??
    dw   scriptOpCodeDF                                ;; 02:4590 ??
    dw   scriptOpCodeDF                                ;; 02:4592 ??
    dw   scriptOpCodeDF                                ;; 02:4594 ??
    dw   scriptOpCodeNpc1StepForward                   ;; 02:4596 ..
    dw   scriptOpCodeNpc1StepBackwards                 ;; 02:4598 ??
    dw   scriptOpCodeFA                                ;; 02:459a ??
    dw   scriptOpCodeFA                                ;; 02:459c ??
    dw   scriptOpCodeNpc1DirectionUp                   ;; 02:459e ..
    dw   scriptOpCodeNpc1DirectionDown                 ;; 02:45a0 ..
    dw   scriptOpCodeNpc1DirectionRight                ;; 02:45a2 ..
    dw   scriptOpCodeNpc1DirectionLeft                 ;; 02:45a4 ..
    dw   scriptOpCodeNpc1Delete                        ;; 02:45a6 ??
    dw   scriptOpCodeNpc1SetPosition                   ;; 02:45a8 ??
    dw   scriptOpCode1A                                ;; 02:45aa ??
    dw   scriptOpCode1B                                ;; 02:45ac ??
    dw   scriptOpCodeDF                                ;; 02:45ae ??
    dw   scriptOpCodeDF                                ;; 02:45b0 ??
    dw   scriptOpCodeDF                                ;; 02:45b2 ??
    dw   scriptOpCodeDF                                ;; 02:45b4 ??
    dw   scriptOpCode20                                ;; 02:45b6 ??
    dw   scriptOpCode21                                ;; 02:45b8 ??
    dw   scriptOpCodeFA                                ;; 02:45ba ??
    dw   scriptOpCodeFA                                ;; 02:45bc ??
    dw   scriptOpCode24                                ;; 02:45be ..
    dw   scriptOpCode25                                ;; 02:45c0 ..
    dw   scriptOpCode26                                ;; 02:45c2 ..
    dw   scriptOpCode27                                ;; 02:45c4 ..
    dw   scriptOpCode28                                ;; 02:45c6 ..
    dw   scriptOpCode29                                ;; 02:45c8 ??
    dw   scriptOpCode2A                                ;; 02:45ca ??
    dw   scriptOpCode2B                                ;; 02:45cc ??
    dw   scriptOpCodeDF                                ;; 02:45ce ??
    dw   scriptOpCodeDF                                ;; 02:45d0 ??
    dw   scriptOpCodeDF                                ;; 02:45d2 ??
    dw   scriptOpCodeDF                                ;; 02:45d4 ??
    dw   scriptOpCode30                                ;; 02:45d6 ??
    dw   scriptOpCode31                                ;; 02:45d8 ??
    dw   scriptOpCodeFA                                ;; 02:45da ??
    dw   scriptOpCodeFA                                ;; 02:45dc ??
    dw   scriptOpCode34                                ;; 02:45de ??
    dw   scriptOpCode35                                ;; 02:45e0 ??
    dw   scriptOpCode36                                ;; 02:45e2 ??
    dw   scriptOpCode37                                ;; 02:45e4 ??
    dw   scriptOpCode38                                ;; 02:45e6 ??
    dw   scriptOpCode39                                ;; 02:45e8 ??
    dw   scriptOpCode3A                                ;; 02:45ea ??
    dw   scriptOpCode3B                                ;; 02:45ec ??
    dw   scriptOpCodeDF                                ;; 02:45ee ??
    dw   scriptOpCodeDF                                ;; 02:45f0 ??
    dw   scriptOpCodeDF                                ;; 02:45f2 ??
    dw   scriptOpCodeDF                                ;; 02:45f4 ??
    dw   scriptOpCode40                                ;; 02:45f6 ??
    dw   scriptOpCode41                                ;; 02:45f8 ??
    dw   scriptOpCodeFA                                ;; 02:45fa ??
    dw   scriptOpCodeFA                                ;; 02:45fc ??
    dw   scriptOpCode44                                ;; 02:45fe ??
    dw   scriptOpCode45                                ;; 02:4600 ??
    dw   scriptOpCode46                                ;; 02:4602 ??
    dw   scriptOpCode47                                ;; 02:4604 ??
    dw   scriptOpCode48                                ;; 02:4606 ??
    dw   scriptOpCode49                                ;; 02:4608 ??
    dw   scriptOpCode4A                                ;; 02:460a ??
    dw   scriptOpCode4B                                ;; 02:460c ??
    dw   scriptOpCodeDF                                ;; 02:460e ??
    dw   scriptOpCodeDF                                ;; 02:4610 ??
    dw   scriptOpCodeDF                                ;; 02:4612 ??
    dw   scriptOpCodeDF                                ;; 02:4614 ??
    dw   scriptOpCode50                                ;; 02:4616 ??
    dw   scriptOpCode51                                ;; 02:4618 ??
    dw   scriptOpCodeFA                                ;; 02:461a ??
    dw   scriptOpCodeFA                                ;; 02:461c ??
    dw   scriptOpCode54                                ;; 02:461e ??
    dw   scriptOpCode55                                ;; 02:4620 ??
    dw   scriptOpCode56                                ;; 02:4622 ??
    dw   scriptOpCode57                                ;; 02:4624 ??
    dw   scriptOpCode58                                ;; 02:4626 ??
    dw   scriptOpCode59                                ;; 02:4628 ??
    dw   scriptOpCode5A                                ;; 02:462a ??
    dw   scriptOpCode5B                                ;; 02:462c ??
    dw   scriptOpCodeDF                                ;; 02:462e ??
    dw   scriptOpCodeDF                                ;; 02:4630 ??
    dw   scriptOpCodeDF                                ;; 02:4632 ??
    dw   scriptOpCodeDF                                ;; 02:4634 ??
    dw   scriptOpCode60                                ;; 02:4636 ??
    dw   scriptOpCode61                                ;; 02:4638 ??
    dw   scriptOpCodeFA                                ;; 02:463a ??
    dw   scriptOpCodeFA                                ;; 02:463c ??
    dw   scriptOpCode64                                ;; 02:463e ??
    dw   scriptOpCode65                                ;; 02:4640 ??
    dw   scriptOpCode66                                ;; 02:4642 ??
    dw   scriptOpCode67                                ;; 02:4644 ??
    dw   scriptOpCode68                                ;; 02:4646 ??
    dw   scriptOpCode69                                ;; 02:4648 ??
    dw   scriptOpCode6A                                ;; 02:464a ??
    dw   scriptOpCode6B                                ;; 02:464c ??
    dw   scriptOpCodeDF                                ;; 02:464e ??
    dw   scriptOpCodeDF                                ;; 02:4650 ??
    dw   scriptOpCodeDF                                ;; 02:4652 ??
    dw   scriptOpCodeDF                                ;; 02:4654 ??
    dw   scriptOpCode70                                ;; 02:4656 ??
    dw   scriptOpCode71                                ;; 02:4658 ??
    dw   scriptOpCodeFA                                ;; 02:465a ??
    dw   scriptOpCodeFA                                ;; 02:465c ??
    dw   scriptOpCode74                                ;; 02:465e ??
    dw   scriptOpCode75                                ;; 02:4660 ??
    dw   scriptOpCode76                                ;; 02:4662 ??
    dw   scriptOpCode77                                ;; 02:4664 ??
    dw   scriptOpCode78                                ;; 02:4666 ??
    dw   scriptOpCode79                                ;; 02:4668 ??
    dw   scriptOpCode7A                                ;; 02:466a ??
    dw   scriptOpCode7B                                ;; 02:466c ??
    dw   scriptOpCodeDF                                ;; 02:466e ??
    dw   scriptOpCodeDF                                ;; 02:4670 ??
    dw   scriptOpCodeDF                                ;; 02:4672 ??
    dw   scriptOpCodeDF                                ;; 02:4674 ??
    dw   scriptOpCode80                                ;; 02:4676 ..
    dw   scriptOpCode81                                ;; 02:4678 ..
    dw   scriptOpCodeFA                                ;; 02:467a ??
    dw   scriptOpCodeFA                                ;; 02:467c ??
    dw   scriptOpCode84                                ;; 02:467e ..
    dw   scriptOpCode85                                ;; 02:4680 ..
    dw   scriptOpCode86                                ;; 02:4682 ..
    dw   scriptOpCode87                                ;; 02:4684 ..
    dw   scriptOpCodeSetFastMovement                   ;; 02:4686 ..
    dw   scriptOpCodeClearFastMovement                 ;; 02:4688 ..
    dw   scriptOpCode8A                                ;; 02:468a ..
    dw   scriptOpCodePlayerJump                        ;; 02:468c ??
    dw   scriptOpCodeFA                                ;; 02:468e ??
    dw   scriptOpCodeFA                                ;; 02:4690 ??
    dw   scriptOpCodeFA                                ;; 02:4692 ??
    dw   scriptOpCode8F                                ;; 02:4694 ??
    dw   scriptOpCode90                                ;; 02:4696 ??
    dw   scriptOpCode91                                ;; 02:4698 ??
    dw   scriptOpCodeFA                                ;; 02:469a ??
    dw   scriptOpCodeFA                                ;; 02:469c ??
    dw   scriptOpCode94                                ;; 02:469e ??
    dw   scriptOpCode95                                ;; 02:46a0 ??
    dw   scriptOpCode96                                ;; 02:46a2 ??
    dw   scriptOpCode97                                ;; 02:46a4 ??
    dw   scriptOpCode98                                ;; 02:46a6 ??
    dw   scriptOpCode99                                ;; 02:46a8 ??
    dw   scriptOpCode9A                                ;; 02:46aa ??
    dw   scriptOpCode9B                                ;; 02:46ac ??
    dw   scriptOpCodeGiveFollower                      ;; 02:46ae ..
    dw   scriptOpCode9D                                ;; 02:46b0 ??
    dw   scriptOpCodeDF                                ;; 02:46b2 ??
    dw   scriptOpCodeDF                                ;; 02:46b4 ??
    dw   scriptOpCodeA0                                ;; 02:46b6 ??
    dw   scriptOpCodeA1                                ;; 02:46b8 ??
    dw   scriptOpCodeA2                                ;; 02:46ba ??
    dw   scriptOpCodeA3                                ;; 02:46bc ??
    dw   scriptOpCodeSetPlayerNormalSprite             ;; 02:46be ..
    dw   scriptOpCodeSetPlayerHurtSprite               ;; 02:46c0 ..
    dw   scriptOpCodeSetPlayerLaydownSprite            ;; 02:46c2 ..
    dw   scriptOpCodeDF                                ;; 02:46c4 ??
    dw   scriptOpCodeDF                                ;; 02:46c6 ??
    dw   scriptOpCodeA9                                ;; 02:46c8 ..
    dw   scriptOpCodeAA                                ;; 02:46ca ??
    dw   scriptOpCodeAB                                ;; 02:46cc ..
    dw   scriptOpCodeOpenMap                           ;; 02:46ce ..
    dw   scriptOpCodeWaitMapClose                      ;; 02:46d0 ..
    dw   scriptOpCodeCloseMap                          ;; 02:46d2 ..
    dw   scriptOpCodeAF                                ;; 02:46d4 ..
    dw   scriptOpCodeSetRoomTile                       ;; 02:46d6 ..
    dw   scriptOpCodeDF                                ;; 02:46d8 ??
    dw   scriptOpCodeDF                                ;; 02:46da ??
    dw   scriptOpCodeDF                                ;; 02:46dc ??
    dw   scriptOpCodeDF                                ;; 02:46de ??
    dw   scriptOpCodeDF                                ;; 02:46e0 ??
    dw   scriptOpCodeB6                                ;; 02:46e2 ??
    dw   scriptOpCodeB7                                ;; 02:46e4 ??
    dw   scriptOpCodeB8                                ;; 02:46e6 ??
    dw   scriptOpCodeB9                                ;; 02:46e8 ??
    dw   scriptOpCodeBA                                ;; 02:46ea ??
    dw   scriptOpCodeDF                                ;; 02:46ec ??
    dw   scriptOpCodeFadeToNormal                      ;; 02:46ee ..
    dw   scriptOpCodeFadeToBlack                       ;; 02:46f0 ..
    dw   scriptOpCodeFadeToWhite                       ;; 02:46f2 ??
    dw   scriptOpCodeFlashScreen                       ;; 02:46f4 ..
    dw   scriptOpCodeFA                                ;; 02:46f6 ..
    dw   scriptOpCodeC1                                ;; 02:46f8 ..
    dw   scriptOpCodeC2                                ;; 02:46fa ??
    dw   scriptOpCodeC3                                ;; 02:46fc ??
    dw   scriptOpCodeC4                                ;; 02:46fe ..
    dw   scriptOpCodeC5                                ;; 02:4700 ..
    dw   scriptOpCodeC6                                ;; 02:4702 ..
    dw   scriptOpCodeC7                                ;; 02:4704 ??
    dw   scriptOpCodeC8                                ;; 02:4706 ..
    dw   scriptOpCodeC9                                ;; 02:4708 ..
    dw   scriptOpCodeCA                                ;; 02:470a ??
    dw   scriptOpCodeCB                                ;; 02:470c ??
    dw   scriptOpCodeCC                                ;; 02:470e ??
    dw   scriptOpCodeDF                                ;; 02:4710 ??
    dw   scriptOpCodeDF                                ;; 02:4712 ??
    dw   scriptOpCodeDF                                ;; 02:4714 ??
    dw   scriptOpCodeD0                                ;; 02:4716 ??
    dw   scriptOpCodeD1                                ;; 02:4718 ..
    dw   scriptOpCodeD2                                ;; 02:471a ??
    dw   scriptOpCodeD3                                ;; 02:471c ??
    dw   scriptOpCodeD4                                ;; 02:471e ..
    dw   scriptOpCodeD5                                ;; 02:4720 ??
    dw   scriptOpCodeD6                                ;; 02:4722 ??
    dw   scriptOpCodeD7                                ;; 02:4724 ??
    dw   scriptOpCodeD8                                ;; 02:4726 ??
    dw   scriptOpCodeD9                                ;; 02:4728 ??
    dw   scriptOpCodeDA                                ;; 02:472a ..
    dw   scriptOpCodeDB                                ;; 02:472c ..
    dw   scriptOpCodeDC                                ;; 02:472e ..
    dw   scriptOpCodeDD                                ;; 02:4730 ..
    dw   scriptOpCodeDE                                ;; 02:4732 ??
    dw   scriptOpCodeDF                                ;; 02:4734 ??
    dw   scriptOpCodeE0                                ;; 02:4736 ..
    dw   scriptOpCodeE1                                ;; 02:4738 ??
    dw   scriptOpCodeE2                                ;; 02:473a ??
    dw   scriptOpCodeE3                                ;; 02:473c ??
    dw   scriptOpCodeE4                                ;; 02:473e ??
    dw   scriptOpCodeE5                                ;; 02:4740 ??
    dw   scriptOpCodeE6                                ;; 02:4742 ??
    dw   scriptOpCodeE7                                ;; 02:4744 ??
    dw   scriptOpCodeScrollRoomDown                    ;; 02:4746 ..
    dw   scriptOpCodeScrollRoomUp                      ;; 02:4748 ??
    dw   scriptOpCodeScrollRoomLeft                    ;; 02:474a ..
    dw   scriptOpCodeScrollRoomRight                   ;; 02:474c ..
    dw   scriptOpCodeRunRoomScript                     ;; 02:474e ..
    dw   scriptOpCodeED                                ;; 02:4750 ??
    dw   scriptOpCodeEE                                ;; 02:4752 ??
    dw   scriptOpCodeEF                                ;; 02:4754 ..
    dw   scriptOpCodeF0                                ;; 02:4756 ..
    dw   scriptOpCodeFA                                ;; 02:4758 ??
    dw   scriptOpCodeFA                                ;; 02:475a ??
    dw   scriptOpCodeLoadRoomInstant                   ;; 02:475c ..
    dw   scriptOpCodeLoadRoom                          ;; 02:475e ..
    dw   scriptOpCodeFA                                ;; 02:4760 ??
    dw   scriptOpCodeF6                                ;; 02:4762 ..
    dw   scriptOpCodeFA                                ;; 02:4764 ??
    dw   scriptOpCodeSetMusic                          ;; 02:4766 ..
    dw   scriptOpCodeSFX                               ;; 02:4768 ..
    dw   scriptOpCodeFA                                ;; 02:476a ??
    dw   scriptOpCodeShakeScreen                       ;; 02:476c ??
    dw   scriptOpCodeFC                                ;; 02:476e ..
    dw   scriptOpCodeFD                                ;; 02:4770 ..
    dw   scriptOpCodeSpawnBoss                         ;; 02:4772 ..
    dw   scriptOpCodeFF                                ;; 02:4774 ..
